### ISSUE TITLE
Login error

### ISSUE THREAD

**Issue by sethvincent** [developmentseed/observe-api#45]
When trying to login to the observe dashboard, I see a 500 response from the API. (This is on a staging server)

This happens in the new window that pops up immediately after clicking the login button. It also happens when visiting the api's /login route manually in the browser.

The logs show:

```
Debug: internal, error
    Error: Failed obtaining custom temporary credentials
    at exports.Client.internals.Client.internals.Client._request (/var/www/observe-api/node_modules/@hapi/bell/lib/oauth.js:481:34)
    at process._tickCallback (internal/process/next_tick.js:68:7)
Debug: auth, unauthenticated, error, openstreetmap
    Error: Failed obtaining custom temporary credentials
    at exports.Client.internals.Client.internals.Client._request (/var/www/observe-api/node_modules/@hapi/bell/lib/oauth.js:481:34)
     t process._tickCallback (internal/process/next_tick.js:68:7)
```

I suspect that I might have some config incorrect, though I'm not sure.

**Comment by sethvincent** [comment]
closed by https://github.com/developmentseed/observe-api/pull/51

**Comment by vgeorge** [comment]
I'm afraid PR https://github.com/developmentseed/observe-api/pull/51 might have broken the login flow. I can't authenticate in a local environment, using Firefox or Chrome. This is a recording of a login attempt:

![login](https://user-images.githubusercontent.com/329694/73567485-63312080-445e-11ea-9456-c37f78fa2084.gif)

Firefox opens several popup screens, while in Chrome just one. The response error is the same on both, a 500 error. Server logs are:

```
Debug: internal, error 
    Error: Missing custom request token cookie
    at Object.internals.refreshRedirect (.../dev/observe/custom-bell/lib/oauth.js:377:39)
    at Object.authenticate (.../dev/observe/custom-bell/lib/oauth.js:93:30)
    at module.exports.internals.Manager.execute (.../dev/observe/api/node_modules/@hapi/hapi/lib/toolkit.js:34:36)
    at module.exports.internals.Auth._authenticate (.../dev/observe/api/node_modules/@hapi/hapi/lib/auth.js:256:58)
    at authenticate (.../dev/observe/api/node_modules/@hapi/hapi/lib/auth.js:232:21)
    at Request._lifecycle (.../dev/observe/api/node_modules/@hapi/hapi/lib/request.js:312:68)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

**Comment by sethvincent** [comment]
Dang! I'm not familiar with the `Missing custom request token cookie` error but I can help look into that.

**Comment by vgeorge** [comment]
There was a misconfiguration from my side. The dashboard had `0.0.0.0` as API host, but the server had `localhost`, which caused the cookie error as they are different hostnames. Setting everything to `localhost` or `0.0.0.0` works fine.
